import ProjectDescription
import ProjectDescriptionHelpers

let mainScheme = Scheme(
    name: "ToySwiftUI",
    buildAction: .buildAction(
        targets: [
            .project(path: .relativeToRoot("ToySwiftUI"), target: "ToySwiftUI")
        ]
    ),
    testAction: .testPlans(
        [
            .relativeToRoot("TestPlans/MyTestPlan.xctestplan")
        ]
    ),
    runAction: .runAction(configuration: SettingsDictionary.Phase.debug.name)
)

let workspace = Workspace(
    name: "ToySwiftUI",
    projects: [
        "ToySwiftUI",
        "Modules/**",
    ],
    schemes: [
        mainScheme
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
