import ProjectDescription
import ProjectDescriptionHelpers

let mainScheme = Scheme(
    name: "ToySwiftUI",
    buildAction: .buildAction(
        targets: [
            .project(path: .relativeToRoot("ToySwiftUI"), target: "ToySwiftUI")
        ]
    ),
    testAction: .targets(
        [
//            .init(target: .project(path: "Targets/Network", target: "NetworkTests")),
//            .init(target: .project(path: "Targets/NetworkAlamofire", target: "NetworkAlamofireTests")),
//            .init(target: .project(path: "Targets/NetworkURLSession", target: "NetworkURLSessionTests")),
        ]
    )
)

let workspace = Workspace(
    name: "ToySwiftUI",
    projects: [
        "ToySwiftUI",
        "Modules/**",
    ],
    schemes: [
        mainScheme
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
