require_relative './libs/path_helper.rb'
require_relative './libs/project_helper.rb'

extend PathHelper
extend ProjectHelper


default_platform(:ios)

before_all do
  repository_root = File.expand_path(File.join(__dir__, '../'))
  ENV['FL_ROOT'] = repository_root
  ENV['OUTPUT_DIR'] = File.join(repository_root, 'build', 'output')
  ENV['XCPRETTY_JSON_FILE_OUTPUT'] = File.join(test_reports_path, "errors.json")
  UI.message("Repository_root is #{repository_root}.")
end

########################################################################
# Lanes related to Building and Testing the code
########################################################################
# | Lane         | Configuration            | Scheme                   |
# | -------------|--------------------------|--------------------------|
# | test         | Debug                    | ToySwiftUI               |
# | beta         | Debug                    | ToySwiftUI               |
# | alpha        | alpha                    | ToySwiftUI               |
# | release      | release                  | ToySwiftUI               |
########################################################################

desc "Build Debug"
lane :test do
  run_tests(
    workspace: "ToySwiftUI.xcworkspace",
    scheme: "ToySwiftUI",
    configuration: "Debug",
    device: "iPhone 14 Pro",
    xcodebuild_formatter: "#{xcbeautify_formatter_path} --report junit --report-path #{test_reports_path} --junit-report-filename xcbeautify.junit",
    testplan: "MyTestPlan",
    code_coverage: true,
    result_bundle_path: "#{test_reports_path}/result.xcresult",
    result_bundle: true,
    derived_data_path: derived_data_path,
    output_directory: test_reports_path,
    buildlog_path: test_reports_path,
    reset_simulator: true,
    testplan: "MyTestPlan"
  )
  create_xcpretty_log
  UI.success("test debug😁")
end

desc "Build Debug"
lane :beta do
  build_ios_app(
    scheme: "ToySwiftUI",
    configuration: "Debug",
    destination: "generic/platform=iOS Simulator",
    xcargs: "EXCLUDED_ARCHS=arm64",
    xcodebuild_formatter: xcbeautify_formatter_path,
    derived_data_path: derived_data_path,
    skip_package_ipa: true,
    skip_archive: true,
  )
  UI.success("build debug😁")
end

desc "Build Alpha"
lane :alpha do
  build_ios_app(
    scheme: "ToySwiftUI",
    configuration: "Alpha",
    destination: "generic/platform=iOS Simulator",
    xcargs: "EXCLUDED_ARCHS=arm64",
    xcodebuild_formatter: xcbeautify_formatter_path,
    derived_data_path: derived_data_path,
    skip_package_ipa: true,
    skip_archive: true,
  )

  # upload_symbols_to_crashlytics(
  #   dsym_path: lane_context[SharedValues::DSYM_OUTPUT_PATH],
  #   gsp_path: "#{ENV['FL_ROOT']}/Firebase/GoogleService-Info.plist",
  #   binary_path: "#{derived_data_path}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols",
  # )
  UI.success("build alpha😁")
end

desc "Build Debug"
lane :release do
  UI.success("build release😁")
end

after_all do |lane|
  
end

error do |lane, exception|
  
end

private_lane :create_xcpretty_log do
  log_file = Dir.glob("#{test_reports_path}/*.log").find { true }
  sh("cat '#{log_file}' | \
  xcpretty -f #{xcpretty_formatter_path} \
  --report html --output #{File.join(test_reports_path, "report.html")} \
  --report junit --output #{File.join(test_reports_path, "report.junit")} \
  >>/dev/null 2>&1",
  log: false) if log_file
end
