require_relative './libs/project_helper.rb'

extend ProjectHelper

default_platform(:ios)

before_all do
  repository_root = File.expand_path(File.join(__dir__, '../'))
  ENV['FL_ROOT'] = repository_root
  UI.message("Repository_root is #{repository_root}.")
end

########################################################################
# Lanes related to Building and Testing the code
########################################################################
# | Lane         | Configuration            | Scheme                   |
# | -------------|--------------------------|--------------------------|
# | beta         | Debug                    | ToySwiftUI               |
# | alpha        | alpha                    | ToySwiftUI               |
# | release      | release                  | ToySwiftUI               |
########################################################################


desc "Build Debug"
lane :beta do
  build_ios_app(
    scheme: "ToySwiftUI",
    configuration: "Debug",
    destination: "generic/platform=iOS Simulator",
    xcargs: "EXCLUDED_ARCHS=arm64",
    xcpretty_formatter: xcpretty_formatter_path,
    derived_data_path: "build/DerivedData",
    skip_package_ipa: true,
    skip_archive: true,
  )
  UI.success("build debug😁")
end

desc "Build Alpha"
lane :alpha do
  build_ios_app(
    scheme: "ToySwiftUI",
    configuration: "Alpha",
    destination: "generic/platform=iOS Simulator",
    xcargs: "EXCLUDED_ARCHS=arm64",
    xcpretty_formatter: xcpretty_formatter_path,
    derived_data_path: "build/DerivedData",
    skip_package_ipa: true,
    skip_archive: true,
  )
  UI.success("build alpha😁")
end

desc "Build Debug"
lane :release do
  UI.success("build release😁")
end
