# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Manual AutoMerge

on:
  workflow_dispatch:
        
jobs:
  auto-merge:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout ci-script code
        uses: actions/checkout@v4
        with:
          repository: wooky83/ci-script
          token: ${{ secrets.GH_PAT }}
          path: ci-script
      
      - name: Use bash shell
        shell: bash
        env:
          GITHUB_MERGER_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_APPROVE_TOKEN: ${{ secrets.GH_APPROVE_TOKEN }}
          SLACK_TOKEN: ${{ secrets.GH_SLACK_TOKEN }}
        run : |
          pushd ci-script
          ./auto-merge/auto_merge_runner.sh "wooky83" "ToySwiftUI" "main" "release/v0.0.1" "wookynim" "automerge"
          popd
  