# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Trigger

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration Name'
        required: true
        default: 'Debug'

jobs:
  build:
    name: Manual Build
    uses: ./.github/workflows/workflow.yml

