# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Manual iOS Build & Test

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration Name'
        required: true
        default: 'Debug'
        
jobs:
  build-and-test:
    name: Manual Build and Test
    uses: ./.github/workflows/workflow.yml
