# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR Build & Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache RubyGems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: ${{ runner.os }}-gems-

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'

      - name: Checkout ci-script code
        uses: actions/checkout@v4
        with:
          repository: wooky83/ci-script
          token: ${{ secrets.GH_PAT }}
          path: ci-script

      - name: Install dependencies
        run: sh ./Scripts/bootstrap.sh

      - name: Danger PreBuild
        run: |
          bundle exec danger --dangerfile=ci-script/danger/Dangerfile --danger_id=prebuild --remove-previous-comments
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make test

      - name: Danger Postbuild
        run: bundle exec danger --dangerfile=ci-script/danger/Dangerfile.postbuild --danger_id=postbuild 
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: 'build/output/test-reports/result.xcresult'
        if: success() || failure()
        # ^ This is important because the action will be run
        # even if the test fails in the previous step.

  jira_commit:

    runs-on: ubuntu-latest
      
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      # https://github.com/atlassian/gajira-find-issue-key
      - name: Find in commit messages
        id: jira
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.event.pull_request.title }}
                
      - name: Transition issue
        if: steps.jira.outputs.issue != ''
        id: transition
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.jira.outputs.issue }}
          transitionId: 31
              
          # { id: 11, name: 할 일 } transitions issue to '해야 할 일' status.
          # { id: 21, name: 진행 중 } transitions issue to '진행 중' status.
          # { id: 31, name: 검토중 } transitions issue to '검토 중' status.
          # { id: 41, name: 완료 } transitions issue to '완료됨' status.

