# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Workflow Build

on:
  workflow_call:

jobs:
  build_and_test:
    
    runs-on: macos-13
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache RubyGems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: ${{ runner.os }}-gems-
      
      - name: Install dependencies
        run: sh ./bootstrap.sh

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
        
      - name: skipMacroValidation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        
      - name: Install Tuist
        run: |
          if ! brew list tuist &>/dev/null; then
            echo "Installing Tuist..."
            brew install tuist
          else
            echo "Tuist is already installed."
          fi
      
      - run: make test